In [1]:
import pandas as pd

In [2]:
results = pd.read_csv("../data/results.csv")
drivers = pd.read_csv("../data/drivers.csv")
constructors = pd.read_csv("../data/constructors.csv")

In [3]:
drivers["full_name"] = (
    drivers["forename"] +
    " " +
    drivers["surname"]
)

drivers.head()

,driverId,driverRef,number,code,forename,surname,dob,nationality,url,full_name
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton,Lewis Hamilton
1,2,heidfeld,\N,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld,Nick Heidfeld
2,3,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg,Nico Rosberg
3,4,alonso,14,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso,Fernando Alonso
4,5,kovalainen,\N,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen,Heikki Kovalainen

In [4]:
def top_drivers_by_wins():
    
    winners = results[
        results["positionOrder"] == 1
    ]
    
    win_counts = (
        winners["driverId"]
        .value_counts()
        .head(10)
        .reset_index()
    )
    
    win_counts.columns = [
        "driverId",
        "wins"
    ]
    
    return win_counts.merge(
        drivers[
            ["driverId", "full_name"]
        ],
        on="driverId"
    )

In [5]:
top_drivers_by_wins()

   driverId  wins           full_name
0         1   105      Lewis Hamilton
1        30    91  Michael Schumacher
2       830    63      Max Verstappen
3        20    53    Sebastian Vettel
4       117    51         Alain Prost
5       102    41        Ayrton Senna
6         4    32     Fernando Alonso
7        95    31       Nigel Mansell
8       328    27      Jackie Stewart
9       182    25          Niki Lauda

In [6]:
def top_constructors():
    
    winners = results[
        results["positionOrder"] == 1
    ]
    
    wins = (
        winners["constructorId"]
        .value_counts()
        .head(10)
        .reset_index()
    )
    
    wins.columns = [
        "constructorId",
        "wins"
    ]
    
    return wins.merge(
        constructors[
            ["constructorId", "name"]
        ],
        on="constructorId"
    )

In [7]:
top_constructors()

   constructorId  wins        name
0              6   249     Ferrari
1              1   185     McLaren
2            131   129    Mercedes
3              9   122    Red Bull
4              3   114    Williams
5             32    45  Team Lotus
6              4    35     Renault
7             22    27    Benetton
8             34    23     Brabham
9             25    23     Tyrrell

In [8]:
def driver_stats(driver_id):
    
    driver_results = results[
        results["driverId"] == driver_id
    ]
    
    return {
        "races":
            len(driver_results),
        
        "wins":
            len(
                driver_results[
                    driver_results[
                        "positionOrder"
                    ] == 1
                ]
            ),
        
        "avg_points":
            round(
                driver_results[
                    "points"
                ].mean(),
                2
            )
    }

In [9]:
driver_stats(1)

{'races': 356, 'wins': 105, 'avg_points': np.float64(13.54)}

# Conclusion

Several data analysis tools were created.

These functions will later be connected to a Large Language Model (LLM) so that users can ask questions in natural language and receive data-driven answers.