In [1]:
import pandas as pd

In [2]:
drivers = pd.read_csv("../data/drivers.csv")
constructors = pd.read_csv("../data/constructors.csv")
races = pd.read_csv("../data/races.csv")
results = pd.read_csv("../data/results.csv")

In [3]:
def get_total_drivers():
    return len(drivers)

print(
    get_total_drivers()
)

861

In [4]:
def get_total_races():
    return len(races)

print(
    get_total_races()
)

1125

In [5]:
def get_total_constructors():
    return len(constructors)

print(
    get_total_constructors()
)

212

In [6]:
def get_total_results():
    return len(results)

print(
    get_total_results()
)

26759

In [7]:
def search_driver(name):

    filtered = drivers[
        drivers["surname"]
        .str.contains(
            name,
            case=False,
            na=False
        )
    ]

    return filtered[
        [
            "forename",
            "surname",
            "nationality"
        ]
    ]

In [8]:
search_driver("hamilton")

    forename   surname nationality
0      Lewis  Hamilton     British
708   Duncan  Hamilton     British

In [9]:
def search_constructor(name):

    filtered = constructors[
        constructors["name"]
        .str.contains(
            name,
            case=False,
            na=False
        )
    ]

    return filtered[
        [
            "name",
            "nationality"
        ]
    ]

In [10]:
search_constructor("Ferrari")

                  name nationality
5              Ferrari     Italian
176  De Tomaso-Ferrari     Italian
189     Cooper-Ferrari     British

In [11]:
def search_race(name):

    filtered = races[
        races["name"]
        .str.contains(
            name,
            case=False,
            na=False
        )
    ]

    return filtered[
        [
            "year",
            "name",
            "date"
        ]
    ]

In [12]:
search_race("Australian")

      year                   name        date
0     2009  Australian Grand Prix  2009-03-29
17    2008  Australian Grand Prix  2008-03-16
35    2007  Australian Grand Prix  2007-03-18
54    2006  Australian Grand Prix  2006-04-02
70    2005  Australian Grand Prix  2005-03-06
89    2004  Australian Grand Prix  2004-03-07
107   2003  Australian Grand Prix  2003-03-09
123   2002  Australian Grand Prix  2002-03-03
140   2001  Australian Grand Prix  2001-03-04
157   2000  Australian Grand Prix  2000-03-12
174   1999  Australian Grand Prix  1999-03-07
190   1998  Australian Grand Prix  1998-03-08
206   1997  Australian Grand Prix  1997-03-09
223   1996  Australian Grand Prix  1996-03-10
255   1995  Australian Grand Prix  1995-11-12
271   1994  Australian Grand Prix  1994-11-13
287   1993  Australian Grand Prix  1993-11-07
303   1992  Australian Grand Prix  1992-11-08
319   1991  Australian Grand Prix  1991-11-03
335   1990  Australian Grand Prix  1990-11-04
337   2010  Australian Grand Prix  2010-03-28
370   1989  Australian Grand Prix  1989-11-05
386   1988  Australian Grand Prix  1988-11-13
402   1987  Australian Grand Prix  1987-11-15
418   1986  Australian Grand Prix  1986-10-26
434   1985  Australian Grand Prix  1985-11-03
839   2011  Australian Grand Prix  2011-03-27
858   2012  Australian Grand Prix  2012-03-18
878   2013  Australian Grand Prix  2013-03-17
897   2014  Australian Grand Prix  2014-03-16
921   2015  Australian Grand Prix  2015-03-15
935   2016  Australian Grand Prix  2016-03-20
956   2017  Australian Grand Prix  2017-03-26
976   2018  Australian Grand Prix  2018-03-25
997   2019  Australian Grand Prix  2019-03-17
1059  2022  Australian Grand Prix  2022-04-10
1081  2023  Australian Grand Prix  2023-04-02
1103  2024  Australian Grand Prix  2024-03-24

In [13]:
print(
    "Analysis functions ready."
)

Analysis functions ready.

## Conclusion

In this notebook, we created reusable analysis functions for the F1 GenAI Data Chatbot.

The functions allow us to:

- Retrieve dataset statistics
- Search drivers by name
- Search constructors by name
- Search races by name

These functions act as the analytical layer of the project and provide structured access to Formula 1 information.

In the next notebook, we will connect these functions with Gemini so that the AI can use them as tools to answer user questions about Formula 1 data.